baseURL = "https://elliot-blog.com"

# 主题
theme = "LoveIt"

# 网站标题
title = "技术笔记"

# 默认内容语言
defaultContentLanguage = "zh"
# 语言代码
languageCode = "zh-CN"
# 语言名称
languageName = "中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 版权描述，仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson"]

# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "文章"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "标签"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "分类"
    url = "/categories/"
  [[menu.main]]
    weight = 4
    identifier = "projects"
    name = "个人项目"
    url = "/projects/"
  [[menu.main]]
    weight = 5
    identifier = "about"
    name = "关于我"
    url = "/about/"

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # 公共 git 仓库路径
  gitRepo = "https://github.com/verbannung/verbannung.github.io"
  # 哈希函数用来 SRI
  fingerprint = ""
  # 日期格式
  dateFormat = "2006-01-02"
  # 网站标题，用于 Open Graph 和 Twitter Cards
  title = "技术笔记"
  # 网站描述，用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "GIS开发、算法、图形学技术笔记"
  # 网站图片，用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]

  # 作者配置
  [params.author]
    name = "elliot"
    email = ""
    link = ""

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "技术笔记"
      # 前缀
      pre = ""
      # 后缀
      post = ""
      # 是否为标题显示打字机动画
      typeit = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # 自定义内容
    custom = ""
    # 是否显示 Hugo 和主题信息
    hugo = true
    # 是否显示版权信息
    copyright = true
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2024
    # ICP 备案信息
    icp = ""
    # 许可协议信息
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 应用图标配置
  [params.app]
    # 应用标题
    title = "技术笔记"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # SVG 网站图标
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows 磁贴颜色
    tileColor = "#da532c"

  # 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = "搜索文章..."
    # 最大结果数目
    maxResultLength = 10
    # 结果内容片段长度
    snippetLength = 30
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # 主页信息设置
  [params.home]
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      # 主页显示的网站标题
      title = "好久不见,别来无恙"
      # 主页显示的网站副标题
      subtitle = "欢迎来到我的技术笔记"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # 免责声明
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6

  # 主页的社交信息设置
  [params.social]
    GitHub = "https://github.com/verbannung"
    Linkedin = ""
    X = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Mastodon = ""

  # 文章页面配置
  [params.page]
    # 代码渲染配置
    [params.page.code]
      [params.page.code.render]
        mermaid = false
    # 是否在首页隐藏
    hiddenFromHomepage = false
    # 是否在搜索中隐藏
    hiddenFromSearch = false
    # 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # 是否使用 ruby
    ruby = false
    # 是否使用 fraction
    fraction = false
    # 是否使用 fontawesome
    fontawesome = false
    # 是否显示文章链接到 markdown
    linkToMarkdown = true
    # 是否在 RSS 中显示全部内容
    rssFullContent = false

    # 打赏配置
    reward = true
    rewardAlipay = ""
    rewardWechat = ""
    rewardBTC = ""

    # 文章分享
    [params.page.share]
      enable = true

    # 文章评论
    [params.page.comment]
      enable = true
      # Disqus 评论系统设置
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      # Gitalk 评论系统设置
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine 评论系统设置
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta = ""
        pageSize = 10
        lang = ""
        visitor = false
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        emoji = ""
      # giscus 评论系统设置
      [params.page.comment.giscus]
        enable = true
        repo = "verbannung/verbannung.github.io"
        repoId = "R_kgDOQjonUA"
        category = "General"
        categoryId = "DIC_kwDOQjonUM4Czxom"
        lang = "zh-CN"
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false

    # SEO 配置
    [params.page.seo]
      images = []

  # 网站分析配置
  [params.analytics]
    # Google Analytics
    [params.analytics.google]
      id = "G-HGGT57WBWG"
      respectDoNotTrack = false
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      server = ""
    # Plausible Analytics
    [params.analytics.plausible]
      dataDomain = ""
    # Yandex Metrica
    [params.analytics.yandexMetrica]
      id = ""

  # Cookie 许可配置
  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # CDN 设置
  [params.cdn]
    data = "jsdelivr.yml"

# 代码高亮配置
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = "monokai"

[markup.goldmark.renderer]
  unsafe = true
